spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydb?user=postgres"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect